# Generated by Django 3.1.1 on 2020-09-15 15:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z.-]*', 'Account name should consist of alphanumerics and .- signs'), django.core.validators.MinLengthValidator(2)])),
                ('realm', models.CharField(choices=[('EU', 'Europe'), ('USW', 'US West'), ('USE', 'US East'), ('Asia', 'Asia')], max_length=7)),
                ('last_visited', models.DateTimeField(blank=True, default=None)),
                ('expired', models.BooleanField(blank=True, default=False, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*', 'Character name should consist of letters only.')])),
                ('level', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('char_class', models.CharField(choices=[('Amazon', 'Amazon'), ('Barbarian', 'Barbarian'), ('Necromancer', 'Necromancer'), ('Paladin', 'Paladin'), ('Sorceress', 'Sorceress'), ('Druid', 'Druid'), ('Assassin', 'Assassin')], max_length=11)),
                ('class_image', models.ImageField(blank=True, upload_to='')),
                ('last_visited', models.DateTimeField(blank=True)),
                ('expired', models.BooleanField(blank=True, default=False)),
                ('acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chars', to='manager.account')),
            ],
        ),
    ]
