# Generated by Django 3.1.1 on 2020-09-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20200915_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='expansion',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='hardcore',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='realm',
            field=models.CharField(choices=[('Europe', 'Europe'), ('US West', 'US West'), ('US East', 'US East'), ('Asia', 'Asia')], max_length=7),
        ),
    ]
