# Generated by Django 3.1.1 on 2021-03-09 21:37

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20210206_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='last_visited',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z.-_]*', 'Account name should consist of alphanumerics and .-_ signs'), django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='expansion',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='character',
            name='hardcore',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='character',
            name='last_visited',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
