# Generated by Django 3.1.1 on 2021-03-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_auto_20210309_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='expansion',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='hardcore',
            field=models.BooleanField(default=False),
        ),
    ]
