# Generated by Django 3.1.1 on 2021-03-10 13:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_auto_20210309_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='last_visited',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
