# Generated by Django 3.1.1 on 2021-03-18 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_auto_20210310_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='class_image',
        ),
    ]
