# Generated by Django 3.1.1 on 2021-08-19 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0019_auto_20210501_2205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['id']},
        ),
    ]
