# Generated by Django 3.2.6 on 2021-08-22 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_id'),
        ('manager', '0021_auto_20210822_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='profiles.profile'),
        ),
    ]
