# Generated by Django 3.2.6 on 2021-09-13 11:53

import DoNotExpire.manager.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0022_alter_account_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\_]{2,15}$', "Character's name should consist of letters only and up to one underscore.     It should be between 2 and 15 characters."), DoNotExpire.manager.models.underscore_validator]),
        ),
    ]
