# Generated by Django 3.1.1 on 2020-09-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='expired',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
