# Generated by Django 3.1.1 on 2020-09-15 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20200915_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='last_visited',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z.-]*', 'Account name should consist of alphanumerics and .- signs'), django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='last_visited',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
