# Generated by Django 3.1.1 on 2021-03-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_character_ladder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='ladder',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
