# Generated by Django 3.1.1 on 2021-03-27 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_auto_20210324_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('helmet', models.CharField(default=None, max_length=50)),
                ('armor', models.CharField(default=None, max_length=50)),
                ('belt', models.CharField(default=None, max_length=50)),
                ('gloves', models.CharField(default=None, max_length=50)),
                ('boots', models.CharField(default=None, max_length=50)),
                ('amulet', models.CharField(default=None, max_length=50)),
                ('left_ring', models.CharField(default=None, max_length=50)),
                ('right_ring', models.CharField(default=None, max_length=50)),
                ('main_hand', models.CharField(default=None, max_length=50)),
                ('off_hand', models.CharField(default=None, max_length=50)),
                ('switch_main_hand', models.CharField(default=None, max_length=50)),
                ('switch_off_hand', models.CharField(default=None, max_length=50)),
                ('torch', models.CharField(default=None, max_length=10)),
                ('anni', models.CharField(default=None, max_length=10)),
                ('charms', models.CharField(default=None, max_length=100)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.character')),
            ],
        ),
    ]
