# Generated by Django 3.1.1 on 2021-05-01 20:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0018_auto_20210501_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z\\.\\-\\_]{2,15}$', 'Account name should consist of alphanumerics and ".", "-", "_" signs, and be between 2 and 15 characters.'), django.core.validators.MinLengthValidator(2)]),
        ),
    ]
